### ISSUE TITLE
"The specified engine (ID stable-inpainting-512-v2-0) was not found."

### ISSUE THREAD

**Issue by dcsan** [Stability-AI/stability-sdk#271]
I'm trying to render something using the `2D` animation mode
as soon as I use a `zoom` setting I get this error on rendering.
It's as if the internal render is delegating to another model to handle inpainting when the 2D camera zooms in or out, to fill the scene

```
[pid 35202] [jobid j-0109-015750]:   2%|█▎                                                              | 1/50 [00:04<03:48,  4.65s/it]Received RpcError: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "The specified engine (ID stable-inpainting-512-v2-0) was not found."
	debug_error_string = "UNKNOWN:Error received from peer ipv4:172.64.153.32:443 {created_time:"2024-01-09T01:57:56.417588-05:00", grpc_status:5, grpc_message:"The specified engine (ID stable-inpainting-512-v2-0) was not found."}"
```

**Comment by dcsan** [comment]
full configs

```
using model: stable-diffusion-512-v2-1
img resize for JPG ./revel-images/fusion/sabet/sabet-yellow-girl.jpg
skip resize
inpath contains "mp4" skip resize ./outputs/temp.mp4
completed downloading files
image: ./revel-images/fusion/sabet/sabet-yellow-girl.jpg
video: ./outputs/temp.mp4
using video_init_path: ./outputs/temp.mp4
using init_image: ./revel-images/fusion/sabet/sabet-yellow-girl.jpg
safe_image: ./revel-images/fusion/sabet/sabet-yellow-girl.jpg
animation_settings:
{
  width: 512
  height: 512
  cfg_scale: 12
  sampler: 'DDIM'
  model: 'stable-diffusion-512-v2-1'
  seed: -1
  clip_guidance: 'None'
  init_image: './revel-images/fusion/sabet/sabet-yellow-girl.jpg'
  init_sizing: 'cover'
  mask_path: ''
  mask_invert: false
  animation_mode: '2D'
  max_frames: 50
  border: 'replicate'
  noise_add_curve: '0:(0.02)'
  noise_scale_curve: '0:(1.1)'
  strength_curve: '0:(1), 10:(0.4), 40:(0.4), 49:(0.2)'
  steps_curve: '0:(20)'
  steps_strength_adj: true
  interpolate_prompts: true
  inpaint_border: true
  locked_seed: false
  angle: '0:(0)'
  zoom: '0:(1),50:(0.5)'
  translation_x: '0:(0)'
  translation_y: '0:(0)'
  translation_z: '0:(-0.2)'
  rotation_x: '0:(0)'
  rotation_y: '0:(0)'
  rotation_z: '0:(0)'
  diffusion_cadence_curve: '0:(2)'
  cadence_interp: 'rife'
  cadence_spans: false
  color_coherence: 'LAB'
  brightness_curve: '0:(1.0)'
  contrast_curve: '0:(1.0)'
  hue_curve: '0:(0.0)'
  saturation_curve: '0:(1.0)'
  lightness_curve: '0:(0.0)'
  depth_model_weight: 0.3
  near_plane: 200
  far_plane: 10000
  fov_curve: '0:(25)'
  save_depth_maps: false
  depth_blur_curve: '0:(0.0)'
  depth_warp_curve: '0:(1.0)'
  video_init_path: './outputs/temp.mp4'
  extract_nth_frame: 1
  video_mix_in_curve: '0:(0.2), 10:(0.3), 40:(0.3), 49:(1)'
  video_flow_warp: false
  vr_mode: false
  vr_eye_angle: 0.5
  vr_eye_dist: 5.0
  vr_projection: -0.4
  resume_timestring: ''
  override_settings_path: ''
  non_inpainting_model_for_diffusion_frames: false
  do_mask_fixup: false
  save_inpaint_masks: false
  mask_min_value: '0:(0.0)'
  fps: 10
  camera_type: 'perspective'
  image_render_method: 'mesh'
  image_render_points_per_pixel: 8
  image_render_point_radius: 0.006
  image_max_mesh_edge: 0.1
  mask_render_points_per_pixel: 4
  mask_render_point_radius: 0.0045
  mask_max_mesh_edge: 0.04
  use_inpainting_model: true
  mask_binarization_thr: 0.5
  verbose: true
  accumulate_xforms: false
  midas_weight: 0.3
  negative_prompt: 'blurry, bad hands, ugly, wrinkles'
  negative_prompt_weight: -1
  preset: ''
  color_match_animate: ''
}
```
